# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.3
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.paul.paulsbrawls
archives_base_name=paulsbrawls

# Dependencies
fabric_version=0.116.7+1.21.1

# Custom folder to copy the built mod to.
# Example on Windows: C:/Users/YourUser/AppData/Roaming/.minecraft/mods
# Example on Linux/macOS: /home/user/.minecraft/mods
mods_folder=C:/Users/Paul/Desktop/PaulsBrawlsVanilla/mods
client_mods_folder=C:/Users/Paul/AppData/Roaming/PrismLauncher/instances/PaulsBrawls/.minecraft/mods
